### ISSUE TITLE
使用该template运行关于vuex报错

### ISSUE THREAD

**Issue by Gosixes** [F-loat/mpvue-quickstart#27]
VM804:1 thirdScriptError
Cannot read property 'state' of undefined;at "pages/counter" page lifeCycleMethod onReady function
TypeError: Cannot read property 'state' of undefined
    at Vue$3.mappedState (http://127.0.0.1:39002/appservice/common/vendor.js:6246:32)
    at Watcher.get (http://127.0.0.1:39002/appservice/common/vendor.js:2333:31)
    at Watcher.evaluate (http://127.0.0.1:39002/appservice/common/vendor.js:2437:27)
    at Vue$3.computedGetter [as count] (http://127.0.0.1:39002/appservice/common/vendor.js:2658:23)
    at Vue$3.render (http://127.0.0.1:39002/appservice/pages/counter.js:110:55)
    at Vue$3.Vue._render (http://127.0.0.1:39002/appservice/common/vendor.js:3363:28)
    at Vue$3.updateComponent (http://127.0.0.1:39002/appservice/common/vendor.js:2027:27)
    at Watcher.get (http://127.0.0.1:39002/appservice/common/vendor.js:2333:31)
    at new Watcher (http://127.0.0.1:39002/appservice/common/vendor.js:2322:51)
    at mountComponent (http://127.0.0.1:39002/appservice/common/vendor.js:2031:23)
console.error @ VM804:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
n @ WAService.js:1
e @ appservice?t=1548824427655:3836
r.registerCallback.t @ appservice?t=1548824427655:3836
l.forEach.t @ appservice?t=1548824427655:3836
(anonymous) @ appservice?t=1548824427655:3836
s.onmessage @ appservice?t=1548824427655:3836

**Comment by F-loat** [comment]
初始化之后就有问题吗，选项都选的哪些

**Comment by Gosixes** [comment]
已解决，mpvue与template-compiler版本改为1.0.18.
最后感谢作者提供的模板！
