### ISSUE TITLE
初始化项目后npm run dev报错

### ISSUE THREAD

**Issue by keycz** [F-loat/mpvue-quickstart#28]
TypeError: Cannot read property 'template' of undefined
    at getCompInfo (C:\Users\keycz\my-project\node_modules\mpvue-loader\lib\mp-compiler\util.js:19:61)
    at createPageMPML (C:\Users\keycz\my-project\node_modules\mpvue-loader\lib\mp-compiler\index.js:41:30)
    at resolve (C:\Users\keycz\my-project\node_modules\mpvue-loader\lib\mp-compiler\index.js:196:9)
    at onResolve (C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
    at innerCallback (C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\Resolver.js:143:22)
    at callbackWrapper (C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at next (C:\Users\keycz\my-project\node_modules\tapable\lib\Tapable.js:249:35)
    at C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:39:22
    at callbackWrapper (C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at innerCallback (C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\Resolver.js:143:22)
    at callbackWrapper (C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at next (C:\Users\keycz\my-project\node_modules\tapable\lib\Tapable.js:249:35)
    at innerCallback (C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\Resolver.js:143:22)
    at callbackWrapper (C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at next (C:\Users\keycz\my-project\node_modules\tapable\lib\Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (C:\Users\keycz\my-project\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:41:24)

**Comment by viryHd** [comment]
这个应该不是eslint错，我这边1个月前拉的，去掉eslint的配置就没问题了，现在应该是其他依赖的问题。帮不到你了，

**Comment by keycz** [comment]
用mpvue官方的项目，然后单独安装mpvue-entry后问题解决了。

**Comment by mayingyun** [comment]
初始化下载了mpvue-loader 1.2.0版本，也遇到了这个问题。

**Comment by littlePig-zzf** [comment]
版本的问题，我之前遇到过，后边手动修改mpvue: 1.0.13，mpvue-template-compiler：1.0.13，mpvue-loader：1.1.4，解决了

**Comment by F-loat** [comment]
新版需要调整构建配置，昨天有更新了下，可能还有问题，晚点再看下
